title: Rooben Design
email: roobendesign@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website Designer in La Habra, CA.  Website Design | WordPress 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roobendesign
github_username:  roobendesign

sass:
    sass_dir: _sass

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
